import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:mason/mason.dart';
import 'package:path/path.dart' as p;

import '../../constants/cli_rules.dart';
import '../../generators/slice_generator.dart';
import '../../services/workspace_service.dart';

class SliceRofCommand extends Command<void> {
  final SliceGenerator sliceGenerator;
  final WorkspaceService workspaceService;

  SliceRofCommand({
    required this.sliceGenerator,
    required this.workspaceService,
  }) {
    argParser
      ..addOption('feature', abbr: 'f', help: 'Target feature name.')
      ..addOption('module', abbr: 'm', help: 'Target module name.')
      ..addOption('method', abbr: 'd', help: 'Retrieval method name.')
      ..addOption('dto', help: 'DTO prefix generated by fsda dto.')
      ..addOption('entity', help: 'Entity prefix generated by fsda entity.')
      ..addFlag(
        'list',
        negatable: false,
        help:
            'Generate retrieval flow returning List<Model>. Default return type is single Model.',
      )
      ..addFlag(
        'hook-disabled',
        negatable: false,
        help:
            'Skip post-hook execution and print manual next steps to run afterward.',
      );
  }

  @override
  final String name = 'slice-rof';

  @override
  final String description =
      'Generate retrieval+offline-first slice and reuse existing DTO/Entity artifacts.';

  @override
  String get invocation =>
      'fsda slice-rof <slice> -f <feature> -m <module> -d <method> [--list] --dto <prefix_dto> --entity <prefix_entity> [--hook-disabled]';

  @override
  Future<void> run() async {
    workspaceService.ensureInsideWorkspace(usage);

    final args = argResults!.rest;
    if (args.isEmpty) {
      throw UsageException('Missing slice name.', usage);
    }
    if (args.length > 1) {
      final strayArgs = args.skip(1).join(' ');
      throw UsageException('Unexpected argument(s): "$strayArgs".', usage);
    }

    final slice = args.first;
    final feature = argResults?['feature'] as String?;
    final module = argResults?['module'] as String?;
    final method = argResults?['method'] as String?;
    final dto = argResults?['dto'] as String?;
    final entity = argResults?['entity'] as String?;
    final isList = argResults?['list'] as bool? ?? false;
    final hookDisabled = argResults?['hook-disabled'] as bool? ?? false;

    final missingFlags = <String>[];
    if (feature == null || feature.isEmpty) missingFlags.add('--feature');
    if (module == null || module.isEmpty) missingFlags.add('--module');
    if (method == null || method.isEmpty) missingFlags.add('--method');
    if (dto == null || dto.isEmpty) missingFlags.add('--dto');
    if (entity == null || entity.isEmpty) missingFlags.add('--entity');

    if (missingFlags.isNotEmpty) {
      throw UsageException(
        'Missing required option(s): ${missingFlags.join(', ')}',
        usage,
      );
    }

    final sliceNameRegExp = RegExp(CliRules.sliceNamePattern);
    if (!sliceNameRegExp.hasMatch(slice)) {
      throw UsageException(
        'Invalid slice name "$slice".\n${CliRules.sliceNameRule}',
        usage,
      );
    }

    final featureNameRegExp = RegExp(CliRules.featureNamePattern);
    if (!featureNameRegExp.hasMatch(feature!)) {
      throw UsageException(
        'Invalid feature name "$feature".\n${CliRules.featureNameRule}',
        usage,
      );
    }

    final moduleNameRegExp = RegExp(CliRules.moduleNamePattern);
    if (!moduleNameRegExp.hasMatch(module!)) {
      throw UsageException(
        'Invalid module name "$module".\n${CliRules.moduleNameRule}',
        usage,
      );
    }

    final methodNameRegExp = RegExp(CliRules.methodNamePattern);
    if (!methodNameRegExp.hasMatch(method!)) {
      throw UsageException(
        'Invalid method name "$method".\n${CliRules.methodNameRule}',
        usage,
      );
    }

    final prefixPattern = RegExp(CliRules.sliceArtifactPrefixPattern);
    if (!prefixPattern.hasMatch(dto!)) {
      throw UsageException(
        'Invalid dto prefix "$dto".\n${CliRules.sliceArtifactPrefixRule}',
        usage,
      );
    }
    if (!prefixPattern.hasMatch(entity!)) {
      throw UsageException(
        'Invalid entity prefix "$entity".\n${CliRules.sliceArtifactPrefixRule}',
        usage,
      );
    }

    final normalizedDtoPrefix = _normalizePrefix(dto, 'dto');
    final normalizedEntityPrefix = _normalizePrefix(entity, 'entity');
    final modelPrefix = _resolveModelPrefix(
      dtoPrefix: normalizedDtoPrefix,
      entityPrefix: normalizedEntityPrefix,
    );

    final moduleDir = Directory(
      p.join(Directory.current.path, 'modules', module),
    );
    if (!await moduleDir.exists()) {
      throw UsageException('Module "$module" does not exist.', usage);
    }

    final featureDir = Directory(
      p.join(moduleDir.path, 'lib', 'src', 'features', feature),
    );
    if (!await featureDir.exists()) {
      throw UsageException(
        'Feature "$feature" does not exist in module "$module".',
        usage,
      );
    }

    final dtoSnake = normalizedDtoPrefix.snakeCase;
    final entitySnake = normalizedEntityPrefix.snakeCase;
    final dtoFile = File(
      p.join(featureDir.path, 'data', 'dtos', '${dtoSnake}_dto.dart'),
    );
    final entityFile = File(
      p.join(
        featureDir.path,
        'domain',
        'entities',
        '${entitySnake}_entity.dart',
      ),
    );

    if (!await dtoFile.exists() || !await entityFile.exists()) {
      throw UsageException(
        'DTO/Entity prefixes are not ready in "$feature" feature. Expected files: data/dtos/${dtoSnake}_dto.dart and domain/entities/${entitySnake}_entity.dart. Run fsda dto and fsda entity first.',
        usage,
      );
    }

    await sliceGenerator.generateSliceRof((
      slice: slice,
      feature: feature,
      module: module,
      method: method,
      model: modelPrefix,
      isList: isList,
      hookDisabled: hookDisabled,
    ));
  }

  String _normalizePrefix(String raw, String suffix) {
    final value = raw.trim();
    if (value.isEmpty) {
      return value;
    }

    final lowerValue = value.toLowerCase();
    final lowerSuffix = suffix.toLowerCase();
    final snakeSuffix = '_$lowerSuffix';

    if (lowerValue.endsWith(snakeSuffix)) {
      return value.substring(0, value.length - snakeSuffix.length);
    }

    if (lowerValue.endsWith(lowerSuffix)) {
      return value.substring(0, value.length - lowerSuffix.length);
    }

    return value;
  }

  String _resolveModelPrefix({
    required String dtoPrefix,
    required String entityPrefix,
  }) {
    final dtoModel = dtoPrefix.pascalCase;
    final entityModel = entityPrefix.pascalCase;
    if (dtoModel != entityModel) {
      throw UsageException(
        'DTO prefix "$dtoPrefix" and entity prefix "$entityPrefix" must represent the same model name.',
        usage,
      );
    }

    return dtoModel;
  }
}
