import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:mason/mason.dart';
import 'package:path/path.dart' as p;

import '../../constants/cli_rules.dart';
import '../../generators/slice_generator.dart';
import '../../services/workspace_service.dart';

class SliceMpCommand extends Command<void> {
  final SliceGenerator sliceGenerator;
  final WorkspaceService workspaceService;

  SliceMpCommand({
    required this.sliceGenerator,
    required this.workspaceService,
  }) {
    argParser
      ..addOption('feature', abbr: 'f', help: 'Target feature name.')
      ..addOption('module', abbr: 'm', help: 'Target module name.')
      ..addOption('method', abbr: 'd', help: 'Mutation method name.')
      ..addOption('param', help: 'Param prefix generated by fsda param.')
      ..addOption('request', help: 'Request prefix generated by fsda request.')
      ..addFlag(
        'hook-disabled',
        negatable: false,
        help:
            'Skip post-hook execution and print manual next steps to run afterward.',
      );
  }

  @override
  final String name = 'slice-mp';

  @override
  final String description =
      'Generate mutation+param slice and reuse existing feature artifacts.';

  @override
  String get invocation =>
      'fsda slice-mp <slice> -f <feature> -m <module> -d <method> --param <prefix_param> --request <prefix_request> [--hook-disabled]';

  @override
  Future<void> run() async {
    workspaceService.ensureInsideWorkspace(usage);

    final args = argResults!.rest;
    if (args.isEmpty) {
      throw UsageException('Missing slice name.', usage);
    }
    if (args.length > 1) {
      final strayArgs = args.skip(1).join(' ');
      throw UsageException('Unexpected argument(s): "$strayArgs".', usage);
    }

    final slice = args.first;
    final feature = argResults?['feature'] as String?;
    final module = argResults?['module'] as String?;
    final method = argResults?['method'] as String?;
    final param = argResults?['param'] as String?;
    final request = argResults?['request'] as String?;
    final hookDisabled = argResults?['hook-disabled'] as bool? ?? false;

    final missingFlags = <String>[];
    if (feature == null || feature.isEmpty) missingFlags.add('--feature');
    if (module == null || module.isEmpty) missingFlags.add('--module');
    if (method == null || method.isEmpty) missingFlags.add('--method');
    if (param == null || param.isEmpty) missingFlags.add('--param');
    if (request == null || request.isEmpty) missingFlags.add('--request');

    if (missingFlags.isNotEmpty) {
      throw UsageException(
        'Missing required option(s): ${missingFlags.join(', ')}',
        usage,
      );
    }

    final sliceNameRegExp = RegExp(CliRules.sliceNamePattern);
    if (!sliceNameRegExp.hasMatch(slice)) {
      throw UsageException(
        'Invalid slice name "$slice".\n${CliRules.sliceNameRule}',
        usage,
      );
    }

    final featureNameRegExp = RegExp(CliRules.featureNamePattern);
    if (!featureNameRegExp.hasMatch(feature!)) {
      throw UsageException(
        'Invalid feature name "$feature".\n${CliRules.featureNameRule}',
        usage,
      );
    }

    final moduleNameRegExp = RegExp(CliRules.moduleNamePattern);
    if (!moduleNameRegExp.hasMatch(module!)) {
      throw UsageException(
        'Invalid module name "$module".\n${CliRules.moduleNameRule}',
        usage,
      );
    }

    final methodNameRegExp = RegExp(CliRules.methodNamePattern);
    if (!methodNameRegExp.hasMatch(method!)) {
      throw UsageException(
        'Invalid method name "$method".\n${CliRules.methodNameRule}',
        usage,
      );
    }

    final prefixPattern = RegExp(CliRules.sliceArtifactPrefixPattern);
    if (!prefixPattern.hasMatch(param!)) {
      throw UsageException(
        'Invalid param prefix "$param".\n${CliRules.sliceArtifactPrefixRule}',
        usage,
      );
    }
    if (!prefixPattern.hasMatch(request!)) {
      throw UsageException(
        'Invalid request prefix "$request".\n${CliRules.sliceArtifactPrefixRule}',
        usage,
      );
    }

    final moduleDir = Directory(
      p.join(Directory.current.path, 'modules', module),
    );
    if (!await moduleDir.exists()) {
      throw UsageException('Module "$module" does not exist.', usage);
    }

    final featureDir = Directory(
      p.join(moduleDir.path, 'lib', 'src', 'features', feature),
    );
    if (!await featureDir.exists()) {
      throw UsageException(
        'Feature "$feature" does not exist in module "$module".',
        usage,
      );
    }

    final normalizedParamPrefix = _normalizePrefix(param, 'param');
    final normalizedRequestPrefix = _normalizePrefix(request, 'request');

    final paramFile = File(
      p.join(
        featureDir.path,
        'domain',
        'params',
        '${normalizedParamPrefix.snakeCase}_param.dart',
      ),
    );
    if (!await paramFile.exists()) {
      throw UsageException(
        'Param "$param" is not ready in "$feature" feature. Expected file: domain/params/${normalizedParamPrefix.snakeCase}_param.dart. Run fsda param first.',
        usage,
      );
    }

    final requestFile = File(
      p.join(
        featureDir.path,
        'data',
        'requests',
        '${normalizedRequestPrefix.snakeCase}_request.dart',
      ),
    );
    if (!await requestFile.exists()) {
      throw UsageException(
        'Request "$request" is not ready in "$feature" feature. Expected file: data/requests/${normalizedRequestPrefix.snakeCase}_request.dart. Run fsda request first.',
        usage,
      );
    }

    await sliceGenerator.generateSliceMp((
      slice: slice,
      feature: feature,
      module: module,
      method: method,
      paramPrefix: normalizedParamPrefix,
      requestPrefix: normalizedRequestPrefix,
      hookDisabled: hookDisabled,
    ));
  }

  String _normalizePrefix(String raw, String suffix) {
    final value = raw.trim();
    if (value.isEmpty) {
      return value;
    }

    final lowerValue = value.toLowerCase();
    final lowerSuffix = suffix.toLowerCase();
    final snakeSuffix = '_$lowerSuffix';

    if (lowerValue.endsWith(snakeSuffix)) {
      return value.substring(0, value.length - snakeSuffix.length);
    }

    if (lowerValue.endsWith(lowerSuffix)) {
      return value.substring(0, value.length - lowerSuffix.length);
    }

    return value;
  }
}
